# Move status bar to top
set-option -g status-position top

# Make status bar 2 lines tall
set-option -g status 2

# Current task from Busy on top line
set-option -g status-format[0] "#($HOME/.local/bin/busy)"
set-option -g status-style 'fg=white,bg=black,bold'

# Second line blank for now
set-option -g status-format[1] ""

# Remove window list display
set-option -g window-status-format ""
set-option -g window-status-current-format ""

# Set refresh interval (in seconds)
set-option -g status-interval 2

# I want my ctrl-b back
unbind C-b
set-option -g prefix M-b
bind-key M-b send-prefix

# Bind Alt+b + r to reload config
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# And let me use the trackpad
set-option -g mouse on

# Pass through escape sequences to the shell
set-window-option -g xterm-keys on
